### ISSUE TITLE
distinguish between reading and writing

### ISSUE THREAD

**Issue by nmav** [dwmw2/ietf-cert-best-practice#1]
The text mentions "Applications MUST support format ... " however there is no distinction between writing and reading. That makes a difference. For example an application SHOULD support reading PBES1 encrypted private keys, but MUST support writing PBES2 encrypted private keys with AES.

**Comment by dwmw2** [comment]
Writing keys is outside the scope for client applications. Perhaps we do want to add a section about what we expect from those creating keys though...

**Comment by dwmw2** [comment]
I've added a section on writing keys, and tried to resolve this. But I'm still concerned about feature creep.
